### ISSUE TITLE
Java error on OSX 10 using Matlab R2017a

### ISSUE THREAD

**Issue by schwemro** [DylanMuir/ParforProgMon#2]
Following notification is displayed when using **ParforProgMon**:

> java.net.UnknownHostException: c040039 at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178) at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) at java.net.Socket.connect(Socket.java:579) at java.net.Socket.connect(Socket.java:528) at java.net.Socket.(Socket.java:425) at java.net.Socket.(Socket.java:208) at ParforProgressMonitor$ProgWorker.increment(ParforProgressMonitor.java:57)

**Comment by DylanMuir** [comment]
Hi @schwemro,
Are you running a local or remote pool?

**Comment by schwemro** [comment]
A local.

**Comment by DylanMuir** [comment]
What platform, and what version of the JVM / JDK?

**Comment by marscfeng** [comment]
Same error! Is there anyone can help me out? BTW, parfor or parpool works well on my machine without any java problems.

platform:
`macOS Mojave / MATLAB2018b `
java version:
```
version -java
ans =
    'Java 1.8.0_144-b01 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode'
```
